### ISSUE TITLE
Navigation: a suggestion

### ISSUE THREAD

**Issue by kseistrup** [dvkt/gild#4]
It would be sweet if `gild` could use “raw mode” while reading navigation characters:

1. For starters, display possible selection numbers right-padded with spaces, so that the user doesn't think they have to enter the initial zero, yet still are aligned neatly under each other.
2. In raw mode, all single-char ‘commands’ (even `0`) can be immediately fulfilled without having to use `ENTER`. If the first char is a digit that is _not_ `0`, read another char and see if it is also a digit, then wait for `ENTER`.
3. Having read a complete ‘command’, be it a command or a numerical, you probably want to reset the terminal to ‘cooked mode’ and its original attributes, before acting on the input.

**Comment by xvxx** [comment]
I like this! Originally the goal was to write everything in LDPL, but now that LDPL has a package manager that :ship: has sailed. Maybe it could be an "ldpl-console-input" package or something that `gild` uses.

**Comment by kseistrup** [comment]
I know nothing about LDPL, you're the expert here. :smiley_cat:

**Comment by xvxx** [comment]
I've thought about this a bit - I absolutely love this idea, but I want to keep GILD simple and largely in LDPL. So I think the command-based navigation has to stay, although it could still be improved some. 

This "command line" style navigation seems to be kind of idiomatic to Gopher clients, like `clic` and [cgo](https://github.com/kieselsteini/cgo) and [VF-1](https://github.com/solderpunk/VF-1), which is where I got the idea, so I think that's okay for a Gopher client, even if it's sub-optimal.

That said, I've been working on a Gopher client in another language that uses GILD's aesthetic with your navigation idea and it's really nice. I plan to release it in the next few days. You might be interested in trying it, though I'm not sure if it'll fit all your requirements.

**Comment by kseistrup** [comment]
Now I am curious: Which language is that?

/me hopes it is not nodejs… :wink:

**Comment by xvxx** [comment]
It's in Rust, so it'll be a <1MB standalone binary for Linux and Mac like Gild.

**Comment by xvxx** [comment]
(I wrote JS in a past life for many years, that's one of the reasons I have run back to the warm, tender embrace of terminal apps and tech like Gopher...)

**Comment by xvxx** [comment]
@kseistrup Very first version is up with a gifcast: https://github.com/dvkt/phetch

**Comment by kseistrup** [comment]
That looks beautiful, I'ma try it right away! Thanks!!
