### ISSUE TITLE
Compiling gild v0.2.0 with LDPL v4.4 fails

### ISSUE THREAD

**Issue by kseistrup** [dvkt/gild#5]
ArchLinux has just updated LDPL from v3.0.5 to v4.4 and now I cannot build gild anymore:

```
ldpl -i=gild.cpp -o=gild -f="-march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" gild.ldpl
* Loading gild.ldpl
* Compiling gild.ldpl
LDPL Error: Malformed statement (gild.ldpl:85)
make: *** [Makefile:5: gild] Error 1
```

where 

```sh
$ cat -n ./src/gild-0.2.0/gild.ldpl | grep '    8[0-9]'
    80	            if lines is greater than window.rows then
    81	                store index in gopher.overflow
    82	                break
    83	            end if
    84	            if char is equal to "\n" then
    85	                add 1 and lines in lines
    86	            end if
    87	            in out join out char
    88	            add 1 and index in index
    89	            get character at index from gopher.response in char
```

I don't know anything about LDPL, so I'm completely at a loss here.

**Comment by xvxx** [comment]
Hmm interesting. It looks like it's not successfully including the "compat43.ldpl" file, which is where that `ADD X AND blah...` statement on line 85 is defined.

I have an Arch VM but I'm a newbie - can you share how you installed LDPL? I did `pacman -Ss LDPL` but didn't get anything back.

You also shouldn't need the `-i=gild.cpp` any longer to build Gild, as the new version of LDPL lets us define includes in source code, but I'm getting a different error than you when I use the `-i` so I don't think that's the problem.

**Comment by kseistrup** [comment]
> can you share how you installed LDPL?

I am using [`yay`](https://github.com/Jguer/yay) as AUR helper.

I did a

```sh
$ yay -Sua
```

to update the AUR indices, and it told me there was a new LDPL version available (the v3 thing was already installed from previous build of gild), and I opted to install v4.

To install LDPL for the first time I would

```sh
$ yay -S ldpl
```

and answer any questions `yay` may have.

**Comment by xvxx** [comment]
Very cool, I've got `yay` up and running now. I like how it complains about running as root. I love package managers that don't make me `sudo`.

Maybe it's because I have a fresh install of Arch, but it all worked for me:

````shell
dvkt@archlinux ~> ldpl -v

 This is LDPL version 4.4 'Friendly Falcarius'...
dvkt@archlinux ~/gild> ldpl -o=gild -f="-march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" gild.ldpl
* Loading gild.ldpl
* Compiling gild.ldpl
* Compiling ldpl_socket/ldpl_socket.ldpl
* Compiling compat43.ldpl
* Including C++ extension ldpl_socket/ldpl_socket.cpp
* Including C++ extension gild.cpp
* using C++ switch -march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
* Building gild
* Saved as gild
* File(s) compiled successfully.
````

Is it possible you have an older version of `ldpl` in your path blocking the new one? Or somehow `make`'s version of `ldpl` doesn't match your shell's?

I'm running `
Linux archlinux 4.19.88-1-ec2-lts #1 SMP Tue Dec 10 09:20:03 PST 2019 x86_64 GNU/Linux`.

I installed ldpl with `yay` then `git clone`'d gild and built the clone. Is there another way you're getting gild maybe?

**Comment by kseistrup** [comment]
My version of Linux is 5.4.3, but that shouldn't matter, should it?

> Is it possible you have an older version of `ldpl` in your path blocking the new one?

I never knew LDPL until I need to compile `gild`, and LDPL was installed by `yay`, so that is hardly possible. But I tried removing `gild` _and_ `ldpl`, then said `yay -S gild`. I am then prompted to choose between `ldpl` and `ldpl-git`, but the result is the same for each of them.

I get the same result if I

```
$ git clone https://aur.archlinux.org/gild.git
$ cd gild
$ makepkg -s
==> Making package: gild 0.2.0-1 (2019-12-17T22:49:13 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v0.2.0.tar.gz
  -> Found use-compilation-flags.patch
==> Validating source files with md5sums...
    v0.2.0.tar.gz ... Passed
    use-compilation-flags.patch ... Passed
==> Extracting sources...
  -> Extracting v0.2.0.tar.gz with bsdtar
==> Starting prepare()...
patching file Makefile
==> Removing existing $pkgdir/ directory...
==> Starting build()...
ldpl -i=gild.cpp -o=gild -f="-march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" gild.ldpl
* Loading gild.ldpl
* Compiling gild.ldpl
LDPL Error: Malformed statement (gild.ldpl:85)
make: *** [Makefile:5: gild] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by kseistrup** [comment]
Right, here's the difference:

AUR's [gild package](https://aur.archlinux.org/packages/gild) is downloading `v0.2.0.tar.gz` from the releases. _That_ package refuses to compile here, and it's reproducible.

Running `make build` in the actual gild repository works. But then It's not an ArchLinux package.

**Comment by kseistrup** [comment]
If I clone the git repo here, make a ‘fake’ tarball named v0.2.0.tar.gz, calculate its MD5 sum and insert it at the right place in the PKGBUILD file, then `makepkg` can actually build `gild`.

So it must be something in the downloadable v0.2.0.tar.gz file that makes it impossible to compile with LDPL v4.4.

**Comment by kseistrup** [comment]
It's probably the missing `compat43.ldpl` file.

**Comment by xvxx** [comment]
Ah I see! I didn't realize there was a gild package in AUR, that is very cool. 

Yes you're right about the incompatibility, gild 0.2.0 only works on LDPL 3.x. So I think the solution is to update that package to the latest version of gild. 

I can make a new release of gild right now, but I don't know how to update AUR?

**Comment by iglosiggio** [comment]
Hi! I'm the gild and ldpl mantainer in AUR :)

If you make a new release I will update the aur package accordingly!

In case that you don't want to make a new release I can backport the needed changes in a .patch file and add it to the package. It's just the compat library all that is needed?

**Comment by xvxx** [comment]
@iglosiggio Oh great! Thank you for doing that! 

There is a bit more than the compat library, it now depends on the [ldpl-socket](https://github.com/dvkt/ldpl-socket) library and has some other syntax changes for LDPL 4.x. 

I just [released 0.3.0](https://github.com/dvkt/gild/releases/tag/v0.3.0), although I don't know if the ldpl-socket dependency mucks things up.

**Comment by iglosiggio** [comment]
Updated! :D

* [PKGBUILD diff](https://aur.archlinux.org/cgit/aur.git/commit/?h=gild&id=dc97d09638cd7e8d213bf2ae67884a289903012b)
* [AUR Package](https://aur.archlinux.org/packages/gild/)

**Comment by xvxx** [comment]
Awesome! 

@kseistrup Please try again and let us know if it works.

**Comment by Lartu** [comment]
:heart:

**Comment by kseistrup** [comment]
Everything's cool now. Thanks you, guys!! 👍
